export const selectors = {
  nav: {
    home: '[data-test="nav-home"]',
    categories: '[data-test="nav-categories"]',
    handTools: '[data-test="nav-hand-tools"]',
    contact: '[data-test="nav-contact"]',
    signIn: '[data-test="nav-sign-in"]',
    cart: '[data-test="nav-cart"]',
    menu: '[data-test="nav-menu"]',
    signOut: '[data-test="nav-sign-out"]',
  },
  home: {
    productCard: 'a.card',
    sortDropdown: '[data-test="sort"]',
    searchQuery: '[data-test="search-query"]',
    searchSubmit: '[data-test="search-submit"]',
    languageSelect: '[data-test="language-select"]',
    langDe: '[data-test="lang-de"]',
    productPrice: '[data-test="product-price"]',
    cardTitle: '.card-title',
    sliderMinHandle: 'span.ngx-slider-pointer-min',
    sliderMaxHandle: 'span.ngx-slider-pointer-max',
  },
  contact: {
    firstName: '[data-test="first-name"]',
    lastName: '[data-test="last-name"]',
    email: '[data-test="email"]',
    subject: '[data-test="subject"]',
    message: '[data-test="message"]',
    submit: '[data-test="contact-submit"]',
    attachment: '[data-test="attachment"]',
  },
  auth: {
    emailInput: '[data-test="email"]',
    passwordInput: '[data-test="password"]',
    loginSubmit: '[data-test="login-submit"]',
    deleteButton: '[data-test="delete"]',
    loginError: '[data-test="login-error"]',
    forgotPasswordSubmit: '[data-test="forgot-password-submit"]',
  },
  product: {
    card: 'a.card',
    cardTitle: '.card-title',
    addToCart: '[data-test="add-to-cart"]',
    increaseQuantity: '[data-test="increase-quantity"]',
    decreaseQuantity: '[data-test="decrease-quantity"]',
    addToFavorites: '[data-test="add-to-favorites"]',
    productName: '[data-test="product-name"]',
    quantityInput: '[data-test="quantity"]',
  },
  checkout: {
    cartIcon: '[data-test="nav-cart"]',
    productQuantity: '[data-test="product-quantity"]',
    productPrice: '[data-test="product-price"]',
    linePrice: '[data-test="line-price"]',
    cartTotal: '[data-test="cart-total"]',
    removeItemButton: '.btn.btn-danger',
    cartEmptyMessage: 'app-cart',
    signinTab: '#signin-tab',
    authenticatedMessage: 'p.ng-star-inserted',
    row: 'tr.ng-star-inserted',
  },
  registration: {
    firstName: '[data-test="first-name"]',
    lastName: '[data-test="last-name"]',
    dob: '[data-test="dob"]',
    street: '[data-test="street"]',
    postalCode: '[data-test="postal_code"]',
    city: '[data-test="city"]',
    state: '[data-test="state"]',
    country: '[data-test="country"]',
    phone: '[data-test="phone"]',
    email: '[data-test="email"]',
    password: '[data-test="password"]',
    submit: '[data-test="register-submit"]',
    passwordRevealButton: 'button.btn.btn-outline-secondary',
  },
  ui: {
    toastContainer: 'id=toast-container',
  },
  common: {
    alert: '.alert',
    body: 'body',
  },
  dynamic: {
    fieldError: (field: string) => `[data-test="${field}-error"]`,
    productLink: (productId: string) => `[data-test="product-${productId}"]`,
  },
};